#!/bin/sh
#
# this test script is assumed to be executed in the parent folder
#

FOLDER=tests
MKTESTFS=./mktestfs
TESTFS=./testfs

$MKTESTFS device > /dev/null

# DATA has 63 bytes
# create DATA with 63 * 2^9 = 63 * 512 = 32256 bytes
DATA=abcdefghijklmnopqrstuvwxyz012345ABCDEFGHIJKLMNOPQRSTUVWXYZ67890
i=0;
while [ $i -lt 9 ]; do
    DATA=$DATA$DATA
    i=$(($i+1))
done

FILE=test_rw_large
# save stdout and stderr to file descriptors 3 and 4
# send output of this script to a file
exec < /dev/null 3>&1 4>&2 >$FILE.out 2>&1

cat <<EOF | $TESTFS -n device
create file1
# write to the first indirect block in the double indirect block
write file1 16859136 ab
read file1 16859136 2
stat file1
# write to the first and second indirect blocks in the double indirect block
write file1 33636348 abcdefgh
read file1 33636350 4
stat file1
rm file1
fsstat
create file2
# write close to the largest file size
write file2 34359820200 $DATA
read file2 34359820326 32
read file2 34359852448 8
# read beyond the file size
read file2 34359852456 4
stat file2
fsstat
EOF

cat <<EOF | $TESTFS -n device
stat file1
stat file2
rm file2
fsstat
EOF

# check for any errors in the file system
/cad2/ece344f/tester/bin/cktestfs device

# restore stdout and stderr
exec 1>&3 2>&4

# compare outputs
cmp $FILE.out $FOLDER/$FILE.txt > /dev/null
if [ $? -eq 0 ]; then
    echo PASS;
else
    echo FAIL;
    echo "The output of this script is stored in $FILE.out"
    echo "The output of this script should be $FOLDER/$FILE.txt"
fi
