#!/bin/sh
#
# this test script is assumed to be executed in the parent folder
#

FOLDER=tests
MKTESTFS=./mktestfs
TESTFS=./testfs

$MKTESTFS device > /dev/null

# DATA has 63 bytes
# create DATA with 63 * 2^9 = 63 * 512 = 32256 bytes
DATA=abcdefghijklmnopqrstuvwxyz012345ABCDEFGHIJKLMNOPQRSTUVWXYZ67890
i=0;
while [ $i -lt 9 ]; do
    DATA=$DATA$DATA
    i=$(($i+1))
done

FILE=test_rw
# save stdout and stderr to file descriptors 3 and 4
# send output of this script to a file
exec < /dev/null 3>&1 4>&2 >$FILE.out 2>&1

cat <<EOF | $TESTFS -n device
create file1
# write to block 0
write file1 8190 ab
read file1 8190 2
# write to block 0, 1
write file1 8190 abc
read file1 8190 3
# write to block 9, 1st indirect block 
write file1 81916 abcdefgh
read file1 81919 5
stat file1
rm file1
fsstat
create file2
# write to 4 blocks via indirect block
write file2 16465920 $DATA
read file2 16467936 32
read file2 16498145 31
read file2 16498176 4
stat file2
rm file2
fsstat
EOF

# check for any errors in the file system
/cad2/ece344f/tester/bin/cktestfs device

# restore stdout and stderr
exec 1>&3 2>&4

# compare outputs
cmp $FILE.out $FOLDER/$FILE.txt > /dev/null
if [ $? -eq 0 ]; then
    echo PASS;
else
    echo FAIL;
    echo "The output of this script is stored in $FILE.out"
    echo "The output of this script should be $FOLDER/$FILE.txt"
fi
